name: Update Gradle wrapper

on:
  schedule: [{cron: "0 4 * * 1"}]
  workflow_dispatch:
    branches:
      - dev

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@main
        with:
          target-branch: dev
          repo-token: ${{ secrets.MY_TOKEN }}
          set-distribution-checksum: true
          paths: V2rayNG/gradle/wrapper/*
